### ISSUE TITLE
Help using step

### ISSUE THREAD

**Issue by troelsarvin** [estokes/libgssapi#12]
I'm trying to understand how to set up a complete client context, but I'm stuck. The test code is here: [https://troels.arvin.dk/rust/libgssapi/1/](https://troels.arvin.dk/rust/libgssapi/1/). It tries to set up a gssapi context against a Kerberos-enabled database server.

I call the resulting little program like this:
`gsstest "postgres/servername.somedomain.local"`

The resulting output suggests that the first step goes well, but the second one fails:

```
client_ctx initially:
ClientCtx { ctx: 0x0, cred: CredInfo { name: troels@SOMEDOMAIN.LOCAL, lifetime: 31161s, usage: Initiate, mechanisms: [GSS_MECH_KRB5] }, target: postgres/servername.somedomain.local@SOMEDOMAIN.LOCAL, flags: GSS_C_MUTUAL_FLAG, state: Uninitialized, mech: Some(GSS_MECH_KRB5) }

is_complete: false, s1: Some(Buf(gss_buffer_desc_struct { length: 1515, value: 0x55eaeaadd9c0 }))
s2: Err(Error { major: GSS_S_BAD_MECH | GSS_S_NO_CONTEXT | GSS_S_DEFECTIVE_TOKEN, minor: 100001 })
```

What have I misunderstood?

I know my Kerberos state of affairs is OK when running the test program, since I can connect to the database like this (not entering any password):

```
$ psql -h servername.somedomain.local
psql (14.3)
GSSAPI-encrypted connection
Type "help" for help.

troels=#
```

And output from "klist" includes this:

```
19-02-2023 13:06:15  19-02-2023 23:05:10  postgres/servername.somedomain.local@
	renew until 26-02-2023 13:05:10
	Ticket server: postgres/servername.somedomain.local@SOMEDOMAIN.LOCAL
```

**Comment by fogti** [comment]
well, step is supposed to get it's input from the server it is interacting with, and its output is supposed to be sent to the server. it can't be called iteratively on its own output, it is supposed to negotiate with a server.
