### ISSUE TITLE
ServerCtx vs ClientCtx cred

### ISSUE THREAD

**Issue by AndrewJackson2020** [estokes/libgssapi#27]
Looking through the code I notice that in libgssapi/src/context.rs ClientCtx allows Option<Cred> whereas ServerCtx requires a Cred value. Any reason for this? 

I believe that this makes it impossible to replicate the postgres style GSS process that can be seen in [
libpq](https://github.com/postgres/postgres/blob/master/src/backend/libpq/auth.c) for example.

https://github.com/postgres/postgres/blob/master/src/backend/libpq/auth.c

**Comment by AndrewJackson2020** [comment]
Thank you for actioning this, greatly appreciated.

**Comment by estokes** [comment]
Not a problem, it's a trivial fix, gssapi is so complex I'm resigned to the fact that this will never end :joy:
