### ISSUE TITLE
compilation failing

### ISSUE THREAD

**Issue by aanavaneeth** [estokes/libgssapi#4]
hello!

when i tried the example from read me, the compilation is failing with below error message.
````
thread 'main' panicked at 'Unable to find libclang: "the `libclang` shared library at /usr/lib64/clang-private/libclang.so.7 could not be opened: libclangAST.so.7: cannot open shared object file: No such file or directory"'
````
I could see that the folder is available but not sure if its a permission issue. Is there an alternative i can consider to get this working?

**Comment by estokes** [comment]
What os are you using? You're not trying to cross compile are you?

**Comment by estokes** [comment]
In any case, bindgen depends on libclang. So whatever package provides it
needs to be installed before bindgen can work. Bindgen is needed during the
build process to parse the gssapi header files and generate the low level
interface.

**Comment by aanavaneeth** [comment]
hi. Thank you so much for such a quick response! I am on RHEL server with /usr/li64 being a shared folder. Also with MIT kerberos

**Comment by aanavaneeth** [comment]
is there a way I can download my own clang compiler and configure this to work with my local compiler folder? not sure if this work but just wanted to check.

**Comment by estokes** [comment]
If you look carefully at the error message, it seems libclangAST.so.7 is
missing from your shared folder.

**Comment by aanavaneeth** [comment]
no. its not missing from the location. I double checked it. I am wondering if its a permission issue which i am not sure can be resolved by sysadmins. Thats why checking if there is an alternative or not

**Comment by estokes** [comment]
You might get that to work if you add your custom clang install to
LD_LIBRARY_PATH in bindgen's environment. It's probably not quite that
simple, but if you can't properly install libclang something like that
might work.

Though, if I were you I'd build whatever you're building on a workstation I
had control of, and then deploy the binary to the server. libclang is only
required for building, there's no reason to have it in a production
environment.

**Comment by aanavaneeth** [comment]
as you suggested, I setup my local copy of clang compiler and updated LD_LIBRARY_PATH path pointing to that. Compilation succeeded!! Thank you so much!! :)
